name: Build and Push to Docker Hub

on:
  release:
    types: [created]

# Environment variables available to all jobs and steps in this workflow
env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  setup-build-publish-deploy:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      
    # Build the Docker image
    - name: Build
      run: |        
       docker run --rm -v $PWD/output:/output -v $PWD/model:/model dmoutinho/archimatetool --html.createReport /output/report --loadModel /model/model.archimate

    # Push the Docker image
    - name: Push
      run: |        
       docker build -t dmoutinho/hello-archi:$(echo $GITHUB_REF | cut -d / -f 3) .
       docker login --username "$DOCKER_USER" --password "$DOCKER_PASSWORD"
       docker push dmoutinho/hello-archi:$(echo $GITHUB_REF | cut -d / -f 3)
       docker logout
