name: Build and Push to Docker Hub

on:
  release:
    types: [created]

# Environment variables available to all jobs and steps in this workflow

jobs:
  setup-build-publish-deploy:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      
    # Build the Docker image
    - name: Build
      run: |        
        echo $PWD
        ls $PWD
